- docs/_config.yml
Needed to pass the dashboard check
> Update `repository` in website's `_config.yml`

- docs/DeveloperGuide.md
> [Docs] Add use cases

- docs/_config.yml
> Update `title` in `_config.yml`

- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
- src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Forgot to modify storage components to store remarks while implementing. Issues are not fixed. Related test files are updated as well.
> Fix issue where remarks cannot be saved.

- src/main/java/seedu/address/ui/TargetPersonCard.java
- src/main/java/seedu/address/ui/TargetPersonPanel.java
- src/main/resources/view/LightTheme.css
- src/main/resources/view/TargetPersonCard.fxml
Closes #53 and #54 
Details of the bugs that this PR fixes can be found in the issues. Additionally, abstracted `TargetPersonCard` as its own component instead of reusing `PersonListCard` so that we can apply different styling changes and show reminders in it in the future.
> UI bug fixes

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/Ui.java
- src/main/java/seedu/address/ui/UiManager.java
Adds a launch message to display to the user when the user launches the app. This is used to show feedback to the user whenever `Storage` fails to read from the data file while launching the app.
Closes #47
> Add launch message

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
- src/main/java/seedu/address/logic/commands/TagCommand.java
- src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
- src/main/java/seedu/address/logic/parser/TagCommandGroupParser.java
- src/main/java/seedu/address/logic/parser/TagCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/tag/Tag.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/ui/TargetPersonCard.java
- src/main/java/seedu/address/ui/TargetPersonPanel.java
- src/main/resources/view/TargetPersonCard.fxml
- src/test/java/seedu/address/logic/commands/RemoveTagCommandTest.java
- src/test/java/seedu/address/logic/commands/TagCommandTest.java
- src/test/java/seedu/address/model/tag/TagTest.java
#13
- Tags cannot contain numerals only
- Tags will be **added** to the target person when no index is provided
- Tags will be **removed** from the target person when no index is provided
- Sample data generated will have the default tags created within the storage file
- Added additional tests for tagging feature
- Added show command related tests for tagging feature
> Update tag feature to support show command

- src/main/java/seedu/address/logic/commands/FilterClearCommand.java
- src/main/java/seedu/address/logic/commands/FilterCommand.java
- src/main/java/seedu/address/logic/parser/FilterCommandParser.java
- src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
> Update error messages and tooltips for filter command

- src/main/java/seedu/address/logic/commands/TagCommandGroup.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/TagCommandParser.java
- src/main/java/seedu/address/model/tag/Tag.java
#63 
Ban specific tag names to integrate well with the show command and command aliasing.
> Ban specific tag names

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/CreateMessageCommand.java
- src/main/java/seedu/address/logic/commands/CreateTagCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/DeleteMessageCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/FilterClearCommand.java
- src/main/java/seedu/address/logic/commands/FilterCommand.java
- src/main/java/seedu/address/logic/commands/GenerateMessageCommand.java
- src/main/java/seedu/address/logic/commands/ListMessageCommand.java
- src/main/java/seedu/address/logic/commands/MessageCommandGroup.java
- src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
- src/main/java/seedu/address/logic/commands/ShowCommand.java
- src/main/java/seedu/address/logic/commands/TagCommandGroup.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/FilterCommandParser.java
- src/main/java/seedu/address/logic/parser/MessageCommandGroupParser.java
- src/main/java/seedu/address/logic/parser/TagCommandGroupParser.java
#40 
- AddCommand: a
- DeleteCommand: d
- EditCommand: e
- FilterCommand: f
- FilterClearCommand: f c
- ShowCommand: s
- TagCommand: t
- CreateTagCommand: t c
- RemoveTagCommand: t r
- MessageCommand: m
- CreateMessageCommand: m c
- ListMessageCommand: m l
- GenerateMessageCommand: m g
- DeleteMessageCommand: m d
> Command aliasing

- .github/codecov.yml
waiting on codecov to comment on this PR to verify that it works
> Update codecov to ignore UI code

- src/main/java/seedu/address/logic/commands/HomeCommand.java
- src/main/java/seedu/address/logic/commands/ReminderClearCommand.java
- src/main/java/seedu/address/logic/commands/ReminderCommandGroup.java
- src/main/java/seedu/address/logic/commands/ReminderDeleteCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/FilterCommandParser.java
- src/main/java/seedu/address/logic/parser/ReminderCommandGroupParser.java
#40
- HomeCommand: h
- FilterListCommand: f l
- ReminderCreateCommand: r
- ReminderClearCommand: r c
- ReminderDeleteCommand: r d
> Add command aliases for home, reminder, filter commands

- src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
- src/main/java/seedu/address/logic/commands/TagCommandGroup.java
- src/main/java/seedu/address/logic/parser/TagCommandGroupParser.java
> Add alias for delete tag command

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/FilterClearCommand.java
- src/main/java/seedu/address/logic/commands/FilterCommand.java
- src/main/java/seedu/address/logic/commands/TagCommand.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/TagMatchesQueryPredicate.java
- src/test/java/seedu/address/logic/commands/FilterCommandTest.java
- src/test/java/seedu/address/logic/commands/TagCommandTest.java
> Disallow filter with non-existant tags

- src/main/java/seedu/address/logic/commands/ReminderClearCommand.java
- src/main/java/seedu/address/logic/commands/ReminderDeleteCommand.java
- src/main/java/seedu/address/model/reminder/DateTime.java
- src/test/java/seedu/address/logic/commands/ReminderClearCommandTest.java
- src/test/java/seedu/address/logic/commands/ReminderCreateCommandTest.java
- src/test/java/seedu/address/logic/commands/ReminderDeleteCommandTest.java
- src/test/java/seedu/address/logic/parser/DateTimeParserTest.java
- src/test/java/seedu/address/logic/parser/ReminderCommandGroupParserTest.java
- src/test/java/seedu/address/logic/parser/ReminderCreateCommandParserTest.java
- src/test/java/seedu/address/logic/parser/ReminderDeleteCommandParserTest.java
- src/test/java/seedu/address/model/reminder/DateTimeTest.java
- src/test/java/seedu/address/model/reminder/ReminderListTest.java
- src/test/java/seedu/address/model/reminder/ReminderTest.java
- src/test/java/seedu/address/testutil/TypicalReminders.java
Added test cases for feature-reminders.
> Feature reminders test cases

- src/main/java/seedu/address/logic/parser/FilterCommandParser.java
- src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
> Fix bug where TargetPerson tag cannot be removed

- docs/UserGuide.md
Fix a few formatting errors for consistency. Add details for filter list and tag deletion.
> [Docs] UG FilterList and TagDeletion Command

- docs/UserGuide.md
Updated intro, added glossary and added UI screenshot
> [Docs] Add intro to UG

- src/main/java/seedu/address/logic/commands/ListTagCommand.java
- src/main/java/seedu/address/logic/commands/TagCommandGroup.java
- src/main/java/seedu/address/logic/commands/TagListCommand.java
- src/main/java/seedu/address/logic/parser/TagCommandGroupParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/tag/TagSet.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
> Tag list command

- .github/workflows/gradle.yml
- build.gradle
- src/main/java/seedu/address/logic/commands/GenerateMessageCommand.java
- src/main/java/seedu/address/model/reminder/DateTime.java
- src/main/java/seedu/address/model/reminder/Reminder.java
- src/main/java/seedu/address/ui/ReminderCard.java
- src/main/java/seedu/address/ui/WelcomePanel.java
- src/main/resources/view/LightTheme.css
* Expired reminders are now displayed red.
* Reminder cards now shows their indexes
* Generated messages now copies to clipboard automatically
> Reminder & Message Template updates

- docs/UserGuide.md
Closes #119 #120 #122 #125 #127 #129 #133 #134
Closes #118
> PE-D documentation reports fixes

- docs/UserGuide.md
> Fix non-alphanumeric tag names in UG

- src/main/java/seedu/address/logic/commands/AddCommand.java
> Add missing space in `add` example

- docs/UserGuide.md
> Fix broken link to reminders

- docs/UserGuide.md
> Fix wrong example for `message generate`

- src/main/java/seedu/address/logic/parser/ReminderCreateCommandParser.java
- src/test/java/seedu/address/logic/parser/ReminderCreateCommandParserTest.java
> Add limit on reminder description length

- docs/AboutUs.md
Feel free to edit this PR if changes should be made
> [Docs] Update roles and responsibilities in AboutUs page

- docs/UserGuide.md
> [Docs] Add tag field to add and edit in UG

- src/main/java/seedu/address/logic/commands/AddCommand.java
> Make `AddCommand` check if the given tags exist

- docs/UserGuide.md
> [Docs] Add section for tag list in UG

- src/main/java/seedu/address/logic/commands/DeleteCommand.java
> Delete `Person` shown will return to home panel

- src/main/java/seedu/address/model/person/Phone.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
- src/test/java/seedu/address/model/person/PhoneTest.java
- src/test/java/seedu/address/model/person/TagMatchesQueryPredicateTest.java
> Update phone number regex to at least 7 digits

- src/main/resources/view/TargetPersonPanel.fxml
> Fix UI labels

- docs/DeveloperGuide.md
> Add manual testing instructions for reminders

- src/main/java/seedu/address/logic/commands/CreateMessageCommand.java
- src/main/java/seedu/address/logic/commands/DeleteMessageCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/ListMessageCommand.java
- src/main/java/seedu/address/logic/commands/ReminderDeleteCommand.java
- src/main/java/seedu/address/model/person/Email.java
- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/model/person/EmailTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
* Update regex for email to ensure domain names have `.`
* Message commands that modifies message list (i.e. create, delete) now switch secondary pane to the message panel in order to show the user the results of their command.
* Likewise for delete reminder command (create reminder command not affected).
* Check of equalness of a `Person` is now only matches name and phone number (as they are primary keys for reminders)
* Name checks are no longer caps sensitive
> More bug fixes

- docs/team/craeyeons.md
> [Docs] PPP for craeyeons

- docs/DeveloperGuide.md
- docs/UserGuide.md
Tries to revert the table of contents back to the repo we forked from
> Try to fix table of contents for DG and UG
